services:
  - type: web
    name: colaboraread-bot
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x ./setup_chrome.sh && ./setup_chrome.sh && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORTAL_USERNAME
        sync: false
      - key: PORTAL_PASSWORD
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
